version: '3'

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - 8080:80
    volumes:
      - ${PWD}/config/nginx.conf:/etc/nginx/nginx.conf:Z

  phpfpm:
    image: bitnami/php-fpm:latest
    depends_on:
      - db
    networks:
      - app-tier
    volumes:
      - ${PWD}/src:/app:Z

  db:
    image: postgres:alpine
    networks:
      - app-tier
    env_file:
      - ${PWD}/config/db_env
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app-tier:
    driver: bridge

volumes:
  pgdata:
