version: '3'

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - 8080:80
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf

  phpfpm:
    image: bitnami/php-fpm:latest
    networks:
      - app-tier
    volumes:
      - ${PWD}/src:/app

networks:
  app-tier:
    driver: bridge

