version: '3.8'

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - 8080:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:z

  phpfpm:
    build:
      context: .
      dockerfile: ./config/Dockerfile
    depends_on:
      - db
    networks:
      - app-tier
    volumes:
      - ./src:/app:z

  composer:
    image: composer:latest
    command: composer install --ignore-platform-reqs
    volumes:
      - ./src:/app:z

  db:
    image: postgres:alpine
    networks:
      - app-tier
    ports:
      - 5432:5432
    env_file:
      - ./config/db_env
    volumes:
      - pgdata:/var/lib/postgresql/data:z

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - app-tier
    ports:
      - 8888:8888
    env_file:
      - ./config/db_env

networks:
  app-tier:
    driver: bridge

volumes:
  pgdata:
