version: '3.8'

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - 8080:80
    volumes:
      - ${PWD}/config/nginx.conf:/etc/nginx/nginx.gconf:z

  phpfpm:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/config/Dockerfile
    depends_on:
      - db
    networks:
      - app-tier
    volumes:
      - ${PWD}/src:/app:z

  composer:
    image: composer:latest
    command: composer install --ignore-platform-reqs
    volumes:
      - ${PWD}/src:/app:z

  db:
    image: postgres:alpine
    networks:
      - app-tier
    ports:
      - 5432:5432
    env_file:
      - ${PWD}/config/db_env
    volumes:
      - pgdata:/var/lib/postgresql/data:z

networks:
  app-tier:
    driver: bridge

volumes:
  pgdata:
